document.documentElement.classList.add("js");
document.addEventListener("DOMContentLoaded",()=>{
  const contactSelectors=[".contact-page-hero .container",".contact-directory-heading",".contact-info-card",".contact-maps-heading",".contact-map-card",".contact-form-copy",".contact-form-section .form-card",".compact-cta-inner"];
  if(document.querySelector(".contact-page-hero")){
    const revealItems=document.querySelectorAll(contactSelectors.join(","));
    revealItems.forEach((element,index)=>{element.classList.add("contact-reveal");element.style.setProperty("--reveal-delay",`${Math.min(index*65,260)}ms`);});
    revealItems.forEach((element,index)=>{element.style.setProperty("--reveal-delay",`${Math.min(index*65,260)}ms`);});
  }
  const trackingForm=document.querySelector("[data-tracking-form]");
  if(trackingForm){trackingForm.addEventListener("submit",event=>{event.preventDefault();const status=trackingForm.querySelector("[data-tracking-status]");if(status)status.textContent="Sistem tracking publik sedang disiapkan. Hubungi tim kami untuk informasi pengiriman.";});const trackingItems=document.querySelectorAll(".tracking-page-hero .container,.tracking-intro-copy,.tracking-panel,.tracking-step,.tracking-note-inner,.compact-cta-inner");trackingItems.forEach((element,index)=>{element.classList.add("tracking-reveal");element.style.setProperty("--reveal-delay",`${Math.min(index*65,260)}ms`);});}
  const button=document.querySelector("[data-menu]"),nav=document.querySelector("[data-nav]");if(button&&nav){button.addEventListener("click",()=>{const open=nav.classList.toggle("open");button.setAttribute("aria-expanded",String(open));});}document.querySelectorAll("[data-whatsapp-form]").forEach(form=>form.addEventListener("submit",event=>{event.preventDefault();const data=new FormData(form);const labels={nama:"Nama lengkap",perusahaan:"Perusahaan",asal:"Kota asal",tujuan:"Kota tujuan",muatan:"Jenis muatan",volume:"Volume/berat",jadwal:"Jadwal",pesan:"Pesan"};const lines=["Halo Lookman Djaja, saya ingin meminta penawaran pengiriman.",""];Object.entries(labels).forEach(([key,label])=>lines.push(`${label}: ${data.get(key)||"-"}`));window.location.href=`https://wa.me/6281213283987?text=${encodeURIComponent(lines.join("\n"))}`;}));});
